languageCode = "en"
baseURL = "https://blog.dmcindoe.dev"
title = "blog.dmcindoe.dev"
theme = "CodeIT"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "Your Disqus Name" # optional
copyright = "© 2020 Copyright Text"

#[taxonomy]
#    tag = "tags"
#    category = "catergories"
[params]
version = "0.2.X"
description = "My Docs Stack" # optional
headerCover = "images/software-banner.jpg" # optional
footerCover = "images/footerCover.png" # optional
googleAnalyticsUserID = "Your Analytics User Id" # optional

[params.app]
# optional site title override for the app when added to an iOS home screen or Android launcher
title = "LoveIt"
# whether to omit favicon resource links
noFavicon = false
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = ""
# Android browser theme color
themeColor = "#ffffff"
# Safari mask icon color
iconColor = "#5bbad5"
# Windows v8-10 tile color
tileColor = "#da532c"

# Search config
[params.search]
enable = true
# type of search engine ("lunr", "algolia")
type = "lunr"
# max index length of the chunked content
contentLength = 4000
# placeholder of the search bar
placeholder = "search..."
# max number of results length
maxResultLength = 10
# snippet length of the result
snippetLength = 30
# HTML tag name of the highlight part in results
highlightTag = "em"
# whether to use the absolute URL based on the baseURL in search index
absoluteURL = false

[params.search.algolia]
index = "index.en"
appID = "PASDMWALPK"
searchKey = "b42948e51daaa93df92381c8e2ac0f93"

# Home page config
[params.home]
# amount of RSS pages
rss = 10

# Home page profile
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/avatar.png"
# title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page
subtitle = "My Lab Docs Dump!"
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
# disclaimer (HTML format is supported)
disclaimer = ""

# Home page posts
[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 6

# Social config in home page
[params.social]
GitHub = "dMacGit"

#Linkedin = ""
#Twitter = "xxxx"
#Instagram = "xxxx"
#Facebook = "xxxx"
#Telegram = "xxxx"
[menu]

[[menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Posts"
url = "/posts/"
# title will be shown when you hover on this menu link
title = ""
weight = 1

[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 2

[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "Categories"
url = "/categories/"
title = ""
weight = 3

[[menu.main]]
identifier = "about"
pre = ""
name = "about"
url = "/about/"
title = ""
weight = 4

[[menu.main]]
identifier = "github"
pre = "<i class='fab fa-github fa-fw'></i>"
post = ""
name = ""
url = "https://github.com/dMacGit"
title = "GitHub"
weight = 5

# Author config
[author]
name = "David"
email = "d.g.mcindoe@gmail.com"

#link = ""
[permalinks]
post = "/:day/:month/:year/:title/" # optional

[outputs]
  home = ["HTML", "RSS", "JSON"]

# Markup related configuration in Hugo
[markup]

# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
