version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.64
    working_directory: ~/dmcindoedev
    environment:
      HUGO_BUILD_DIR: ~/dmcindoedev/public
      HUGO_SRC_DIR: ~/dmcindoedev
      - run: git submodule sync && git submodule update --init
      - run:
          name: "Build Website with Hugo"
          command: HUGO_ENV=production hugo --buildDrafts --themesDir ~/dmcindoedev/themes
          working_directory: ~/dmcindoedev/public
      - add_ssh_keys:
          fingerprints:
            - "4d:8b:d8:b4:ae:7c:ed:2f:c1:ed:9c:dc:b0:d0:92:e3"
      - deploy:
          name: "Deploy to Linode"
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -azv -e "ssh -o StrictHostKeyChecking=no -p ${DEPLOY_PORT}" --delete ${HUGO_BUILD_DIR}/ ${DEPLOY_USER}@${DEPLOY_HOST}:~/dmcindoedev
            else
              echo "Not master branch, dry run only"
            fi
